backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Texts
        name: texts
        file: cms/_data/texts.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Texts
          - hint: 'Original text: Registration is live!, key: -4396725a'
            label: Text
            name: '-4396725a'
            widget: string
          - hint: 'Original text: April 24-26, 2023, key: -14ccd7d8'
            label: Text
            name: '-14ccd7d8'
            widget: string
          - hint: 'Original text: Austin, TX, key: 25b5eb92'
            label: Text
            name: 25b5eb92
            widget: string
          - hint: 'Original text: Register now, key: -5c165007'
            label: Text
            name: '-5c165007'
            widget: string
          - hint: 'Original text: Organized by:, key: -48378adc'
            label: Text
            name: '-48378adc'
            widget: string
          - hint: >-
              Original text: The Filecoin Network Base is your home base in
              Austin ahead of Consensus 2023. , key: a03da7b
            label: Text
            name: a03da7b
            widget: string
          - hint: >-
              Original text: Visit our co-working space to catch a lightning
              talk, participate in workshops with developers, and learn about
              the latest on the Filecoin Virtual Machine. Spanning three floors,
              packed with programming, networking opportunities, coaching
              sessions and more, the Network Base is your go to spot for cross
              chain collaboration and connections in Austin. , key: -1f2dc793
            label: Text
            name: '-1f2dc793'
            widget: text
          - hint: 'Original text: ‍, key: 200d'
            label: Text
            name: 200d
            widget: string
          - hint: >-
              Original text: The Network base is open daily from 10:00 AM to
              8:00 PM, April 24th through 26th. , key: 7e9a25fd
            label: Text
            name: 7e9a25fd
            widget: string
          - hint: >-
              Original text: Interested in partnering with us or hosting your
              own event in the space? , key: -2e5cdd8f
            label: Text
            name: '-2e5cdd8f'
            widget: string
          - hint: 'Original text: Reach out, key: 33b84301'
            label: Text
            name: 33b84301
            widget: string
          - hint: 'Original text: OUR NETWORK, key: 21b3c91a'
            label: Text
            name: 21b3c91a
            widget: string
          - hint: 'Original text: filecoin.io, key: 46615ca7'
            label: Text
            name: 46615ca7
            widget: string
          - hint: 'Original text: fil.org, key: -330f0881'
            label: Text
            name: '-330f0881'
            widget: string
          - hint: 'Original text: protocol.ai, key: -18777cc2'
            label: Text
            name: '-18777cc2'
            widget: string
          - hint: 'Original text: ABOUT, key: 3b32b6d'
            label: Text
            name: 3b32b6d
            widget: string
          - hint: 'Original text: Code of Conduct, key: -24630032'
            label: Text
            name: '-24630032'
            widget: string
          - hint: 'Original text: Privacy Policy, key: -3fbde6f6'
            label: Text
            name: '-3fbde6f6'
            widget: string
          - hint: >-
              Original text: Copyright © 2023 Filecoin Foundation, key:
              -4ad5204b
            label: Text
            name: '-4ad5204b'
            widget: string
          - hint: 'Original text: 繁體, key: fe4b3'
            label: Text
            name: fe4b3
            widget: string
          - hint: 'Original text: Join us for DeStor HK!, key: -72596ba'
            label: Text
            name: '-72596ba'
            widget: string
          - hint: >-
              Original text: Calling all Filecoin Storage Providers, Clients &
              Investors, key: b1ded90
            label: Text
            name: b1ded90
            widget: string
          - hint: 'Original text: Apply for your FREE Ticket now!, key: 6f7afeaf'
            label: Text
            name: 6f7afeaf
            widget: string
          - hint: 'Original text: A FREE ticket to , key: da3ba46'
            label: Text
            name: da3ba46
            widget: string
          - hint: 'Original text: Filecoin DeStorHK, key: -382d8f65'
            label: Text
            name: '-382d8f65'
            widget: string
          - hint: >-
              Original text:  gets you full-day access to Web3 Festival on the
              15th of April, Limit one ticket per application; full-access pass
              restricted to Web3 Festival 4/15/23. , key: 2204869f
            label: Text
            name: 2204869f
            widget: text
          - hint: >-
              Original text: What’s the next step for your storage provider
              business?, key: 31f3e313
            label: Text
            name: 31f3e313
            widget: string
          - hint: 'Original text: Come to , key: -209dc1f7'
            label: Text
            name: '-209dc1f7'
            widget: string
          - hint: 'Original text: DeStor HK, key: 50ec12be'
            label: Text
            name: 50ec12be
            widget: string
          - hint: >-
              Original text:  - a half day event created specifically for , key:
              -250ce4b0
            label: Text
            name: '-250ce4b0'
            widget: string
          - hint: 'Original text: Filecoin Storage Providers, key: -43444236'
            label: Text
            name: '-43444236'
            widget: string
          - hint: "Original text: .\_ This event offers a unique opportunity to connect with other providers, hear from experts at Protocol Labs and your peers, and learn new strategies for maximizing your storage business and capabilities.\_ You’ll gain insights into the latest developments in blockchain technology (like FVM) and how they are evolving and revolutionizing your business potential.\_ You will also have the chance to explore new collaboration opportunities that will also help grow your business through improved utility and efficiency.\_ , key: 41f166ab"
            label: Text
            name: 41f166ab
            widget: text
          - hint: >-
              Original text:  is a must-attend event as you look to stay ahead
              of the curve and drive your business forward., key: -2d1c6d2c
            label: Text
            name: '-2d1c6d2c'
            widget: text
          - hint: 'Original text: 加入我們參加DeStor HK, key: -2aa6fea4'
            label: Text
            name: '-2aa6fea4'
            widget: string
          - hint: 'Original text: ENGLISH, key: -34cbd9b0'
            label: Text
            name: '-34cbd9b0'
            widget: string
          - hint: 'Original text: 呼叫所有的Filecoin存儲提供者、客戶和投資者。, key: -33d00093'
            label: Text
            name: '-33d00093'
            widget: string
          - hint: 'Original text: 立即申請您的免費門票！, key: 339ff2ef'
            label: Text
            name: 339ff2ef
            widget: string
          - hint: >-
              Original text: 免費的Filecoin
              DeStorHK門票可以讓您在4月15日全天進入Web3節慶，每個申請只限制一張門票；完全通行證僅限於Web3節慶4/15/23。,
              key: 4e7f3364
            label: Text
            name: 4e7f3364
            widget: string
          - hint: 'Original text: 你的存儲服務業務下一步是什麼？, key: -7450ab72'
            label: Text
            name: '-7450ab72'
            widget: string
          - hint: >-
              Original text: 快來參加DeStor
              HK——這是專為Filecoin存儲服務提供商設計的半天活動。本次活動為您提供了與其他提供商聯繫、聆聽Protocol
              Labs和您的同行專家意見、學習最大化您的存儲業務和能力的新策略的獨特機會。您將獲得有關區塊鏈技術（如FVM）的最新發展及其如何演進和革新您的業務潛力的深入見解。您還有機會探索新的合作機會，通過提高實用性和效率來幫助增長業務。對於想要保持領先並推動業務前進的人來說，DeStor
              HK是必參加的活動。, key: 5a8f6439
            label: Text
            name: 5a8f6439
            widget: text
          - hint: >-
              Original text: Register here to join the Filecoin community and
              our partners this April 24-26 at the , key: 2b0d9730
            label: Text
            name: 2b0d9730
            widget: string
          - hint: 'Original text: Filecoin Network Base., key: -37ee0de8'
            label: Text
            name: '-37ee0de8'
            widget: string
      - label: Links
        name: links
        file: cms/_data/links.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Links
          - hint: 'Original link: /register, key: f6c8fd2'
            label: Link
            name: f6c8fd2
            widget: string
          - hint: 'Original link: http://fil.org, key: -197dcad3'
            label: Link
            name: '-197dcad3'
            widget: string
          - hint: 'Original link: mailto:events@fil.org, key: 42500560'
            label: Link
            name: '42500560'
            widget: string
          - hint: 'Original link: https://filecoin.io/, key: 1f2c24b7'
            label: Link
            name: 1f2c24b7
            widget: string
          - hint: 'Original link: https://fil.org/, key: 2058645f'
            label: Link
            name: 2058645f
            widget: string
          - hint: 'Original link: https://protocol.ai/, key: -5d162f00'
            label: Link
            name: '-5d162f00'
            widget: string
          - hint: >-
              Original link:
              https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md,
              key: -10a93b9c
            label: Link
            name: '-10a93b9c'
            widget: string
          - hint: >-
              Original link: https://fil.org/policy/#site-navigation, key:
              9d271d5
            label: Link
            name: 9d271d5
            widget: string
          - hint: 'Original link: /destor-zh, key: 4fbd56a7'
            label: Link
            name: 4fbd56a7
            widget: string
          - hint: 'Original link: /destor-en, key: 4fbd5422'
            label: Link
            name: 4fbd5422
            widget: string
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: i13e1af84
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: i7b9971c6
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 6e53f5b
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 66c5b85
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-511e189f'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 101fa572
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: df0ffdb
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '76412e4'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
publish_mode: editorial_workflow
